//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunpnMesWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MesWebSoap")]
    public interface MesWebSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 InterfaceNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Call", ReplyAction="*")]
        SunpnMesWeb.ServiceReference1.CallResponse Call(SunpnMesWeb.ServiceReference1.CallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Call", ReplyAction="*")]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.CallResponse> CallAsync(SunpnMesWeb.ServiceReference1.CallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownFile", ReplyAction="*")]
        SunpnMesWeb.ServiceReference1.DownFileResponse DownFile(SunpnMesWeb.ServiceReference1.DownFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.DownFileResponse> DownFileAsync(SunpnMesWeb.ServiceReference1.DownFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SunpnMesWeb.ServiceReference1.HelloWorldResponse HelloWorld(SunpnMesWeb.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SunpnMesWeb.ServiceReference1.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Call", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.CallRequestBody Body;
        
        public CallRequest() {
        }
        
        public CallRequest(SunpnMesWeb.ServiceReference1.CallRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InterfaceNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Params;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AttachParams;
        
        public CallRequestBody() {
        }
        
        public CallRequestBody(string InterfaceNo, string Params, string AttachParams) {
            this.InterfaceNo = InterfaceNo;
            this.Params = Params;
            this.AttachParams = AttachParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallResponse", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.CallResponseBody Body;
        
        public CallResponse() {
        }
        
        public CallResponse(SunpnMesWeb.ServiceReference1.CallResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallResult;
        
        public CallResponseBody() {
        }
        
        public CallResponseBody(string CallResult) {
            this.CallResult = CallResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownFile", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.DownFileRequestBody Body;
        
        public DownFileRequest() {
        }
        
        public DownFileRequest(SunpnMesWeb.ServiceReference1.DownFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FilePath;
        
        public DownFileRequestBody() {
        }
        
        public DownFileRequestBody(string ServerFileName, string FilePath) {
            this.ServerFileName = ServerFileName;
            this.FilePath = FilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.DownFileResponseBody Body;
        
        public DownFileResponse() {
        }
        
        public DownFileResponse(SunpnMesWeb.ServiceReference1.DownFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message;
        
        public DownFileResponseBody() {
        }
        
        public DownFileResponseBody(byte[] DownFileResult, string Message) {
            this.DownFileResult = DownFileResult;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SunpnMesWeb.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SunpnMesWeb.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SunpnMesWeb.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MesWebSoapChannel : SunpnMesWeb.ServiceReference1.MesWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesWebSoapClient : System.ServiceModel.ClientBase<SunpnMesWeb.ServiceReference1.MesWebSoap>, SunpnMesWeb.ServiceReference1.MesWebSoap {
        
        public MesWebSoapClient() {
        }
        
        public MesWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunpnMesWeb.ServiceReference1.CallResponse SunpnMesWeb.ServiceReference1.MesWebSoap.Call(SunpnMesWeb.ServiceReference1.CallRequest request) {
            return base.Channel.Call(request);
        }
        
        public string Call(string InterfaceNo, string Params, string AttachParams) {
            SunpnMesWeb.ServiceReference1.CallRequest inValue = new SunpnMesWeb.ServiceReference1.CallRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.CallRequestBody();
            inValue.Body.InterfaceNo = InterfaceNo;
            inValue.Body.Params = Params;
            inValue.Body.AttachParams = AttachParams;
            SunpnMesWeb.ServiceReference1.CallResponse retVal = ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).Call(inValue);
            return retVal.Body.CallResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.CallResponse> SunpnMesWeb.ServiceReference1.MesWebSoap.CallAsync(SunpnMesWeb.ServiceReference1.CallRequest request) {
            return base.Channel.CallAsync(request);
        }
        
        public System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.CallResponse> CallAsync(string InterfaceNo, string Params, string AttachParams) {
            SunpnMesWeb.ServiceReference1.CallRequest inValue = new SunpnMesWeb.ServiceReference1.CallRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.CallRequestBody();
            inValue.Body.InterfaceNo = InterfaceNo;
            inValue.Body.Params = Params;
            inValue.Body.AttachParams = AttachParams;
            return ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).CallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunpnMesWeb.ServiceReference1.DownFileResponse SunpnMesWeb.ServiceReference1.MesWebSoap.DownFile(SunpnMesWeb.ServiceReference1.DownFileRequest request) {
            return base.Channel.DownFile(request);
        }
        
        public byte[] DownFile(string ServerFileName, string FilePath, out string Message) {
            SunpnMesWeb.ServiceReference1.DownFileRequest inValue = new SunpnMesWeb.ServiceReference1.DownFileRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.DownFileRequestBody();
            inValue.Body.ServerFileName = ServerFileName;
            inValue.Body.FilePath = FilePath;
            SunpnMesWeb.ServiceReference1.DownFileResponse retVal = ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).DownFile(inValue);
            Message = retVal.Body.Message;
            return retVal.Body.DownFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.DownFileResponse> SunpnMesWeb.ServiceReference1.MesWebSoap.DownFileAsync(SunpnMesWeb.ServiceReference1.DownFileRequest request) {
            return base.Channel.DownFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.DownFileResponse> DownFileAsync(string ServerFileName, string FilePath) {
            SunpnMesWeb.ServiceReference1.DownFileRequest inValue = new SunpnMesWeb.ServiceReference1.DownFileRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.DownFileRequestBody();
            inValue.Body.ServerFileName = ServerFileName;
            inValue.Body.FilePath = FilePath;
            return ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).DownFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunpnMesWeb.ServiceReference1.HelloWorldResponse SunpnMesWeb.ServiceReference1.MesWebSoap.HelloWorld(SunpnMesWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SunpnMesWeb.ServiceReference1.HelloWorldRequest inValue = new SunpnMesWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.HelloWorldRequestBody();
            SunpnMesWeb.ServiceReference1.HelloWorldResponse retVal = ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.HelloWorldResponse> SunpnMesWeb.ServiceReference1.MesWebSoap.HelloWorldAsync(SunpnMesWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SunpnMesWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SunpnMesWeb.ServiceReference1.HelloWorldRequest inValue = new SunpnMesWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SunpnMesWeb.ServiceReference1.HelloWorldRequestBody();
            return ((SunpnMesWeb.ServiceReference1.MesWebSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
